[global]
log_level = 'info'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = false

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 1000
clear_on_start = true
#filter = true
tx_confirmation = true

[telemetry]
enabled = true
host = 'X.X.X.X'
port = 3000

[[chains]]
id = 'axelar-dojo-1'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr = 'GRPC_ENDPOINT'
event_source = { mode = 'pull', interval = '200ms' }
rpc_timeout = '120s'
account_prefix = 'axelar'
key_name = 'axelar'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.007, denom = 'uaxl' }
gas_multiplier = 1.2
clock_drift ='5s'
trusting_period = '5days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-17'], # Ki
   ['transfer', 'channel-21'], # Fetch
   ['transfer', 'channel-32'], # Bitcanna
   ['transfer', 'channel-75'], # Kyve
   ['transfer', 'channel-135'], # huahua
]

[[chains]]
id = 'bitcanna-1'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr = 'GRPC_ENDPOINT'
event_source = { mode = 'pull', interval = '200ms' }
rpc_timeout = '120s'
account_prefix = 'bcna'
key_name = 'bcna'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.01, denom = 'ubcna' }
gas_multiplier = 1.2
clock_drift = '10s'
trusting_period = '806400s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-1'], # osmosis
   ['transfer', 'channel-3'], # cosmos
   ['transfer', 'channel-8'], # gravity
   ['transfer', 'channel-15'], # axelar
]

[[chains]]
id = 'cosmoshub-4'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr = 'GRPC_ENDPOINT'
event_source = { mode = 'pull', interval = '200ms' }
rpc_timeout = '30s'
account_prefix = 'cosmos'
key_name = 'cosmos'
store_prefix = 'ibc'
max_tx_size = 180000
max_gas = 2000000
gas_price = { price = 0.005, denom = 'uatom' }
gas_multiplier = 1.2
clock_drift = '10s'
trusting_period = '806400s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
  ['transfer', 'channel-223'], # Kichain
  ['transfer', 'channel-232'], # Bitcanna
  ['transfer', 'channel-277'], # Kava
  ['transfer', 'channel-526'], # Fetch
]

[[chains]]
id = 'fetchhub-4'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr = 'GRPC_ENDPOINT'
event_source = { mode = 'pull', interval = '200ms' }
rpc_timeout = '120s'
account_prefix = 'fetch'
key_name = 'fetch'
store_prefix = 'ibc'
max_tx_size = 179000
max_gas = 2000000
gas_price = { price = 2, denom = 'afet' }
gas_multiplier = 1.2
clock_drift = '10s'
trusting_period = '1209600s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-10'], # Osmosis
   ['transfer', 'channel-14'], # Axelar
   ['transfer', 'channel-16'], # Cosmoshub
]

[[chains]]
id = 'gitopia'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr = 'GRPC_ENDPOINT'event_source = { mode = 'pull', interval = '200ms' }
rpc_timeout = '120s'
account_prefix = 'gitopia'
key_name = 'gitopia'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.0, denom = 'ulore' }
gas_multiplier = 1.5
clock_drift ='5s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-0'], # osmo
]


[[chains]]
id = 'gravity-bridge-3'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr = 'GRPC_ENDPOINT'
event_source = { mode = 'pull', interval = '200ms' }
rpc_timeout = '120s'
account_prefix = 'gravity'
key_name = 'grav'
store_prefix = 'ibc'
max_gas = 1200000
gas_price = { price = 0.001, denom = 'ugraviton' }
gas_multiplier = 1.2
clock_drift ='15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-0'], # Bitcanna
   ['transfer', 'channel-37'], # Kichain
]

[[chains]]
id = 'kava_2222-10'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr = 'GRPC_ENDPOINT'
id = 'kichain-2'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr = 'GRPC_ENDPOINT'
event_source = { mode = 'pull', interval = '200ms' }
rpc_timeout = '120s'
account_prefix = 'ki'
key_name = 'ki'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.025, denom = 'uxki' }
gas_multiplier = 1.2
clock_drift = '25s'
trusting_period = '9days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-0'], # Osmosis
   ['transfer', 'channel-1'], # Cosmos
   ['transfer', 'channel-11'], # Gravity
   ['transfer', 'channel-19'], # Axelar
   ['wasm.ki1hzz0s0ucrhdp6tue2lxk3c03nj6f60qy463we7lgx0wudd72ctmsd9kgha ', 'channel-18'], # Osmosis-CW20
]

[[chains]]
id = 'osmosis-1'
type = 'CosmosSdk'
rpc_addr =  'RPC_ENDPOINT'
grpc_addr =  'GRPC_ENDPOINT'
event_source = { mode = 'pull', interval = '200ms' }
rpc_timeout = '120s'
account_prefix = 'osmo'
key_name = 'osmosis'
store_prefix = 'ibc'
max_gas = 25000000
max_msg_num = 30
gas_price = { price = 0.025, denom = 'uosmo' }
gas_price_multiplier = 1.1
max_gas_price = 0.6
gas_multiplier = 1.1
default_gas = 300000
max_tx_size = 2097152
clock_drift = '5s'
trusting_period = '9days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-51'], # bitcanna
   ['transfer', 'channel-77'], # kichain
   ['transfer', 'channel-143'], # kava
   ['transfer', 'channel-229'], # Fetch
   ['transfer', 'channel-767'], # Kyve
   ['transfer', 'channel-261'], # Ki CW20
   ['transfer', 'channel-781'], # gitopia
   ['transfer', 'channel-2494'], # passage
]

[[chains]]
id = 'passage-2'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr = 'GRPC_ENDPOINT'
event_source = { mode = 'push', url = 'ws://RPC_ENDPOINT/websocket', batch_delay = '200ms' }
rpc_timeout = '120s'
account_prefix = 'pasg'
key_name = 'passage'
store_prefix = 'ibc'
max_gas = 5000000
gas_price = { price = 0.025, denom = 'upasg' }
gas_multiplier = 1.5
clock_drift ='5s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-0'], # osmo
]


[[chains]]
id = 'kyve-1'
type = 'CosmosSdk'
rpc_addr =  'RPC_ENDPOINT'
grpc_addr =  'GRPC_ENDPOINT'
event_source = { mode = 'pull', interval = '200ms' }
rpc_timeout = '120s'
account_prefix = 'kyve'
key_name = 'kyve'
store_prefix = 'ibc'
max_gas = 2000000
max_msg_num = 30
gas_price = { price = 0.02, denom = 'ukyve' }
gas_multiplier = 1.5
max_tx_size = 1800000
clock_drift = '15s'
trusting_period = '1209600s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-0'], # osmosis
   ['transfer', 'channel-1'], # axelar
]

[[chains]]
id = 'chihuahua-1'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr = 'GRPC_ENDPOINT'
event_source = { mode = 'push', url = 'ws://RPC_ENDPOINT/websocket', batch_delay = '200ms' }
rpc_timeout = '120s'
account_prefix = 'chihuahua'
key_name = 'chihuahua'
store_prefix = 'ibc'
max_gas = 10000000
gas_price = { price = 0.001, denom = 'uhuahua' }
gas_multiplier = 1.2
clock_drift ='15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-78'], # axelar
]