[global]
log_level = 'info'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = false

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 1000
clear_on_start = false
tx_confirmation = true

[telemetry]
enabled = true
host = 'X.X.X.X'
port = 3000

[[chains]]
id = 'laozi-mainnet'
type = 'CosmosSdk'
rpc_addr =  'RPC_ENDPOINT'
grpc_addr =   'GRPC_ENDPOINT'
event_source = { mode = 'pull', interval = '200ms' }
rpc_timeout = '120s'
account_prefix = 'band'
key_name = 'band'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.0025, denom = 'uband' }
gas_multiplier = 1.2
clock_drift = '895s'
trusting_period = '1209600s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['oracle', 'channel-157'], # Desmos
   ['transfer', 'channel-83'], # Osmosis
   ['transfer', 'channel-159'], # Coreum
]

[[chains]]
id = 'coreum-mainnet-1'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr = 'GRPC_ENDPOINT'
event_source = { mode = 'pull', interval = '200ms' }
rpc_timeout = '120s'
account_prefix = 'core'
key_name = 'coreum'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.06, denom = 'ucore' }
gas_multiplier = 1.5
clock_drift ='5s'
trusting_period = '403200s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-7'], # Gravity
   ['transfer', 'channel-20'], # Band
   ['transfer', 'channel-19'], # Noble
]

[[chains]]
id = 'cosmoshub-4'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr = 'GRPC_ENDPOINT'
event_source = { mode = 'pull', interval = '200ms' }
rpc_timeout = '20s'
account_prefix = 'cosmos'
key_name = 'cosmos'
store_prefix = 'ibc'
max_msg_num = 5
max_tx_size = 180000
max_gas = 4000000
default_gas = 1000000
gas_price = { price = 0.005, denom = 'uatom' }
gas_multiplier = 1.5
clock_drift = '15s'
trusting_period = '1209600s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
  ['icahost', 'channel-*'], # lum pool 1 deposit
]

[[chains]]
id = 'desmos-mainnet'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr = 'GRPC_ENDPOINT'
event_source = { mode = 'pull', interval = '200ms' }
rpc_timeout = '120s'
account_prefix = 'desmos'
key_name = 'desmos'
store_prefix = 'ibc'
max_gas = 4000000
gas_price = { price = 0.01, denom = 'udsm' }
gas_multiplier = 1.2
clock_drift = '25s'
trusting_period = '9days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-2'], # Osmosis
   ['ibc-profiles', 'channel-32'], # Band
]

[[chains]]
id = 'evmos_9001-2'
type = 'CosmosSdk'
rpc_addr =  'https://rpc.evmos.nodestake.top:443' #'http://65.108.70.119:57657'  #'https://rpc-evmos-ia.cosmosia.notional.ventures'
grpc_addr =  'http://evmos-grpc.w3coins.io:13490'  #'http://grpc-evmos.cosmos-spaces.cloud:1190'
trusted_node = true
event_source = { mode = 'pull', interval = '10s' }
account_prefix = 'evmos'
key_name = 'evmos'
store_prefix = 'ibc'
max_tx_size = 180000
max_gas = 3000000
gas_price = { price = 20000000000, denom = 'aevmos' }
gas_multiplier = 2
clock_drift = '50s'
trusting_period = '84hours'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
address_type = { derivation = 'ethermint', proto_type = { pk_type = '/ethermint.crypto.v1.ethsecp256k1.PubKey' } }
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-87'] # coreum
]

[[chains]]
id = 'gravity-bridge-3'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr = 'GRPC_ENDPOINT'
event_source = { mode = 'pull', interval = '200ms' }
rpc_timeout = '120s'
account_prefix = 'gravity'
key_name = 'grav'
store_prefix = 'ibc'
max_gas = 1200000
gas_price = { price = 0.001, denom = 'ugraviton' }
gas_multiplier = 1.2
clock_drift ='555s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-10'], # Osmosis
   ['transfer', 'channel-107'], # Kujira
   ['transfer', 'channel-142'], #coreum
]

[[chains]]
id = 'kaiyo-1'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr =  'GRPC_ENDPOINT'
event_source = { mode = 'pull', interval = '200ms' }
rpc_timeout = '120s'
account_prefix = 'kujira'
key_name = 'kujira'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.0034, denom = 'ukuji' }
gas_multiplier = 1.2
clock_drift = '5s'
trusting_period = '9days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-3'], # Osmosis
   ['transfer', 'channel-50'], # Gravity
   ['transfer', 'channel-95'], # kava
   ['transfer', 'channel-62'], # Noble
]

[[chains]]
id = 'kava_2222-10'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr = 'GRPC_ENDPOINT'
event_source = { mode = 'push', url = 'ws://RPC_ENDPOINT/websocket', batch_delay = '200ms' }
rpc_timeout = '120s'
account_prefix = 'kava'
key_name = 'kava'
store_prefix = 'ibc'
max_tx_size = 179000
max_gas = 10000000
gas_price = { price = 0.001, denom = 'ukava' }
gas_multiplier = 1.3
clock_drift = '25s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-116'], # Kujira
]

[[chains]]
id = 'lum-network-1'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr = 'GRPC_ENDPOINT'
event_source = { mode = 'pull', interval = '200ms' }
rpc_timeout = '120s'
account_prefix = 'lum'
key_name = 'lum'
store_prefix = 'ibc'
max_gas = 12000000
gas_price = { price = 0.001, denom = 'ulum' }
gas_multiplier = 1.2
clock_drift ='15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-3'], # osmosis
   ['icacontroller-*', 'channel-*'], # ica cosmos 
]

[[chains]]
id = 'osmosis-1'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr = 'GRPC_ENDPOINT'
event_source = { mode = 'pull', interval = '200ms' }
rpc_timeout = '120s'
account_prefix = 'osmo'
key_name = 'osmosis'
gas_price_multiplier = 1.1
max_gas_price = 0.6
store_prefix = 'ibc'
max_gas = 25000000
max_msg_num = 30
gas_price = { price = 0.025, denom = 'uosmo' }
gas_multiplier = 1.1
max_tx_size = 2097152
clock_drift = '15s'
trusting_period = '9days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-113'], # Huahua
   ['transfer', 'channel-115'], # Lum
   ['transfer', 'channel-135'], # Desmos
   ['transfer', 'channel-144'], # Gravity
   ['transfer', 'channel-148'], # Band
   ['transfer', 'channel-259'], # Kujira
   ['transfer', 'channel-362'], # teritori
]

[[chains]]
id = 'teritori-1'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr = 'GRPC_ENDPOINT'
event_source = { mode = 'pull', interval = '200ms' }
rpc_timeout = '120s'
account_prefix = 'tori'
key_name = 'tori'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.00, denom = 'utori' }
gas_multiplier = 1.2
clock_drift ='5s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-0'], # osmo
]

[[chains]]
id = 'noble-1'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr =  'GRPC_ENDPOINT'
event_source = { mode = 'pull', interval = '200ms' }
rpc_timeout = '120s'
account_prefix = 'noble'
key_name = 'noble'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0, denom = 'uusdc' }
gas_multiplier = 1.2
clock_drift ='5s'
trusting_period = '1209600s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer' , 'channel-2' ], # Kujira
   ['transfer', 'channel-49'], # Coreum
]

[[chains]]
id = 'chihuahua-1'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr = 'RPC_ENDPOINT'
event_source = { mode = 'push', url = 'ws://RPC_ENDPOINT/websocket', batch_delay = '200ms' }
rpc_timeout = '120s'
account_prefix = 'chihuahua'
key_name = 'chihuahua'
store_prefix = 'ibc'
max_gas = 10000000
gas_price = { price = 0.001, denom = 'uhuahua' }
gas_multiplier = 1.2
clock_drift ='15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-7'], # osmosis
]