[global]
log_level = 'info'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = false

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 1000
clear_on_start = false
tx_confirmation = true

[telemetry]
enabled = true
host = 'X.X.X.X'
port = 3000

[[chains]]
id = 'axelar-dojo-1'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr = 'GRPC_ENDPOINT'
event_source = { mode = 'pull', interval = '200ms' }
rpc_timeout = '120s'
account_prefix = 'axelar'
key_name = 'axelar'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.01, denom = 'uaxl' }
gas_multiplier = 1.2
clock_drift ='5s'
trusting_period = '403200s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer' , 'channel-116' ], # Provenance
    ['transfer', 'channel-2'], # Cosmos-Hub
]

[[chains]]
id = 'cosmoshub-4'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr = 'GRPC_ENDPOINT'
event_source = { mode = 'pull', interval = '200ms' }
rpc_timeout = '20s'
account_prefix = 'cosmos'
key_name = 'cosmos'
store_prefix = 'ibc'
max_msg_num = 5
max_tx_size = 180000
max_gas = 30000000
default_gas = 1000000
gas_price = { price = 0.005, denom = 'uatom' }
gas_multiplier = 1.5
clock_drift = '15s'
trusting_period = '1209600s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
  ['transfer', 'channel-281'], # Gravity
  ['transfer', 'channel-314'], # Provenance
  ['transfer', 'channel-467'], # quicksilver
  ['transfer', 'channel-293'], # Axelar
  ['transfer', 'channel-730'], # Stargaze
]

[[chains]]
id = 'mainnet-3'   # Decentr
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr =    'GRPC_ENDPOINT'
event_source = { mode = 'pull', interval = '200ms' }
rpc_timeout = '120s'
account_prefix = 'decentr'
key_name = 'dec'
store_prefix = 'ibc'
max_gas = 5000000
gas_price = { price = 0.025, denom = 'udec' }
gas_multiplier = 1.2
clock_drift ='15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-1'], # Osmosis
   ['transfer', 'channel-2'], # Gravity
]

[[chains]]
id = 'gravity-bridge-3'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr = 'GRPC_ENDPOINT'
event_source = { mode = 'pull', interval = '200ms' }
rpc_timeout = '120s'
account_prefix = 'gravity'
key_name = 'grav'
store_prefix = 'ibc'
max_gas = 1200000
gas_price = { price = 0.0001, denom = 'ugraviton' }
gas_multiplier = 1.2
clock_drift ='15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-7'], # Stargaze
   ['transfer', 'channel-17'], # Cosmos
   ['transfer', 'channel-58'], # Decentr
]

[[chains]]
id = 'ixo-5'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr = 'GRPC_ENDPOINT'
event_source = { mode = 'pull', interval = '200ms' }
rpc_timeout = '120s'
account_prefix = 'ixo'
key_name = 'ixo-5'
store_prefix = 'ibc'
default_gas = 200000
max_gas = 2000000
gas_price = { price = 0.025, denom = 'uixo' }
gas_multiplier = 7
clock_drift = '15s'
trusting_period = '1209600s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-4'], # Osmosis
   ['transfer', 'channel-26'], # Noble
]

[[chains]]
id = 'noble-1'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr =  'GRPC_ENDPOINT'
event_source = { mode = 'pull', interval = '200ms' }
rpc_timeout = '120s'
account_prefix = 'noble'
key_name = 'noble'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0, denom = 'uusdc' }
gas_multiplier = 1.2
clock_drift ='5s'
trusting_period = '1209600s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer' , 'channel-15' ], # Ixo
    ['transfer' , 'channel-20' ], # Provenance

]

[[chains]]
id = 'osmosis-1'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr = 'GRPC_ENDPOINT'
event_source = { mode = 'pull', interval = '200ms' }
rpc_timeout = '120s'
account_prefix = 'osmo'
key_name = 'osmosis'
store_prefix = 'ibc'
max_gas = 25000000
max_msg_num = 30
gas_price = { price = 0.025, denom = 'uosmo' }
gas_price_multiplier = 1.1
max_gas_price = 0.6
gas_multiplier = 1.1
max_tx_size = 2097152
clock_drift = '15s'
trusting_period = '806400s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-38'], # Ixo
   ['transfer', 'channel-181'], # Decentr
   ['transfer', 'channel-222'], # Provenance
   ['transfer', 'channel-522'], # quicksilver
   ['icahost', 'channel-*'], # ICA
]

[[chains]]
id = 'pio-mainnet-1'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr = 'GRPC_ENDPOINT'
event_source = { mode = 'pull', interval = '200ms' }
rpc_timeout = '120s'
account_prefix = 'pb'
key_name = 'provenance'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 1905, denom = 'nhash' }
gas_multiplier = 1.5
clock_drift = '20s'
trusting_period = '1209600s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'

[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-6'], # Cosmos
   ['transfer', 'channel-7'], # Osmosis
   ['transfer', 'channel-9'], # Axelar
   ['transfer', 'channel-10'], # Noble
]

[[chains]]
id = 'quicksilver-2'
type = 'CosmosSdk'
rpc_addr =  'RPC_ENDPOINT'
grpc_addr = 'GRPC_ENDPOINT'
event_source = { mode = 'pull', interval = '200ms' }
rpc_timeout = '120s'
account_prefix = 'quick'
key_name = 'quick'
store_prefix = 'ibc'
max_gas =100000000
max_msg_num = 5
gas_price = { price = 0.0006, denom = 'uqck' }
gas_multiplier = 1.5
max_tx_size = 1800000
clock_drift = '15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-0'], # stargaze
   ['transfer', 'channel-1'], # Cosmos
   ['transfer', 'channel-2'], # Osmos
   ['icacontroller-stargaze-1.*', 'channel-*'],
   ['icacontroller-osmosis-1.*', 'channel-*'],
]

[[chains]]
id = 'stargaze-1'
type = 'CosmosSdk'
rpc_addr =  'RPC_ENDPOINT'
grpc_addr =   'GRPC_ENDPOINT'
event_source = { mode = 'pull', interval = '200ms' }
rpc_timeout = '120s'
account_prefix = 'stars'
key_name = 'stargaze'
store_prefix = 'ibc'
max_gas = 10000000
max_msg_num = 5
gas_price = { price = 1, denom = 'ustars' }
gas_multiplier = 1.2
clock_drift = '20s'
trusting_period = '777600s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-6'], # Gravity
   ['transfer', 'channel-124'], # Quicksilver
   ['icahost', 'channel-*'], # ICA
   ['transfer', 'channel-239'], # Cosmos
]
