[global]
log_level = 'info'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = false

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 1000
clear_on_start = false
#filter = true
tx_confirmation = true

[telemetry]
enabled = true
host = '192.168.1.250'
port = 3000

[[chains]]
id = 'axelar-dojo-1'
type = 'CosmosSdk'
rpc_addr = 'http://127.0.0.1:32657'
grpc_addr = 'http://127.0.0.1:9097'
event_source = { mode = 'push', url = 'ws://127.0.0.1:32657/websocket', batch_delay = '200ms' }
rpc_timeout = '120s'
account_prefix = 'axelar'
key_name = 'axelar'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.01, denom = 'uaxl' }
gas_multiplier = 1.2
clock_drift ='5s'
max_block_time = '30s'
trusting_period = '403200s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-2'], # Cosmos-Hub
   ['transfer', 'channel-3'], # Osmosis
   ['transfer', 'channel-122'], # Teritori
   ['transfer', 'channel-14'], # Kujira
   ['transfer', 'channel-18'], # Stargaze
   ['transfer', 'channel-114'], # Ixo
   ['transfer', 'channel-120'], # Coreum
   ['transfer', 'channel-125'], # Celestia
]

[[chains]]
id = "celestia"
type = "CosmosSdk"
rpc_addr = "http://127.0.0.1:31657"
grpc_addr = "tcp://127.0.0.1:9890"
event_source = { mode = 'push', url = 'ws://127.0.0.1:31657/websocket', batch_delay = '500ms' }
rpc_timeout = "120s"
account_prefix = "celestia"
key_name = "celestia-key"
store_prefix = "ibc"
gas_price = { price = 0.1, denom = 'utia' }
default_gas = 300000
max_gas = 6000000
gas_multiplier = 1.5
max_msg_num = 20
clock_drift = "5s"
max_block_time = "30s"
memo_prefix = 'Inter Blockchain Services Relayer'
trusting_period = '1209600seconds'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-1'], # axelar
   ['transfer', 'channel-9'], # kujira
 ]

[[chains]]
id = 'coreum-mainnet-1'
type = 'CosmosSdk'
rpc_addr = 'http://192.168.1.55:27657'
grpc_addr = 'http://192.168.1.55:9092'
event_source = { mode = 'push', url = 'ws://192.168.1.55:27657/websocket', batch_delay = '200ms' }
rpc_timeout = '120s'
account_prefix = 'core'
key_name = 'coreum'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.06, denom = 'ucore' }
gas_multiplier = 1.2
clock_drift ='5s'
max_block_time = '30s'
trusting_period = '1209600s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-6'], # Axelar
   ['transfer', 'channel-2'], # Osmo
   ['transfer', 'channel-9'], # Cosmoshub
]

[[chains]]
id = 'cosmoshub-4'
type = 'CosmosSdk'
rpc_addr = 'http://127.0.0.1:33657'
grpc_addr = 'http://127.0.0.1:9098'
event_source = { mode = 'push', url = 'ws://127.0.0.1:33657/websocket', batch_delay = '200ms' }
rpc_timeout = '30s'
account_prefix = 'cosmos'
key_name = 'cosmos'
store_prefix = 'ibc'
max_tx_size = 180000
max_gas = 2000000
gas_price = { price = 0.00, denom = 'uatom' }
gas_multiplier = 1.2
clock_drift = '15s'
max_block_time = '30s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
  ['transfer', 'channel-660'], # Coreum
  ['transfer', 'channel-293'], # Axelar
  ['transfer', 'channel-343'], # Kujira
  ['transfer', 'channel-431'], # Teritori
  ['transfer', 'channel-204'], # ixo
]

[[chains]]
id = 'ixo-5'
type = 'CosmosSdk'
rpc_addr = 'http://192.168.1.53:26657' 
grpc_addr =  'tcp://192.168.1.53:9090' 
event_source = { mode = 'push', url = 'ws://192.168.1.53:26657/websocket', batch_delay = '200ms' }
rpc_timeout = '120s'
account_prefix = 'ixo'
key_name = 'ixo-5'
store_prefix = 'ibc'
default_gas = 200000
max_gas = 2000000
gas_price = { price = 0.5, denom = 'uixo' }
gas_multiplier = 1.3
clock_drift = '15s'
max_block_time = '30s'
trusting_period = '1209600s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-1'], # Cosmos
   ['transfer', 'channel-23'], # Axelar
   ['transfer', 'channel-25'], # Kava
]

[[chains]]
id = 'kaiyo-1'
type = 'CosmosSdk'
rpc_addr = 'http://127.0.0.1:28657' 
grpc_addr =  'tcp://127.0.0.1:9093'
#event_source = { mode = 'push', url = 'ws://127.0.0.1:28657/websocket', batch_delay = '200ms' }
event_source = { mode = 'pull', interval = '1s' }
fee_granter = 'kujira1vkje22mayn72r0a7kna6agv0sqm6k94ry9k6dd'
rpc_timeout = '120s'
account_prefix = 'kujira'
key_name = 'kujira'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.00125, denom = 'ukuji' }
gas_multiplier = 1.2
clock_drift = '5s'
max_block_time = '30s'
trusting_period = '9days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-0'], # Cosmos-Hub
   ['transfer', 'channel-7'], # Stargaze
   ['transfer', 'channel-9'], # Axelar
   ['transfer', 'channel-89'], # Teritori
   ['transfer', 'channel-95'], # Kava
   ['transfer', 'channel-117'], # Celestia
]

[[chains]]
id = 'kava_2222-10'
type = 'CosmosSdk'
rpc_addr = 'http://192.168.1.54:26657'
grpc_addr = 'tcp://192.168.1.54:9090'
event_source = { mode = 'push', url = 'ws://192.168.1.54:26657/websocket', batch_delay = '200ms' }
rpc_timeout = '120s'
account_prefix = 'kava'
key_name = 'kava'
store_prefix = 'ibc'
max_tx_size = 179000
max_gas = 3000000
gas_price = { price = 0.003, denom = 'ukava' }
gas_multiplier = 1.3
clock_drift = '25s'
max_block_time = '30s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-128'], # Ixo
   ['transfer', 'channel-116'], # Kujira
]

[[chains]]
id = 'osmosis-1'
type = 'CosmosSdk'
rpc_addr = 'http://127.0.0.1:26657'
grpc_addr = 'tcp://127.0.0.1:9090'
event_source = { mode = 'pull', interval = '1s' }
rpc_timeout = '120s'
account_prefix = 'osmo'
key_name = 'osmosis'
store_prefix = 'ibc'
max_gas = 6000000
max_msg_num = 10
gas_price = { price = 0.0025 , denom = 'uosmo' }
gas_multiplier = 1.4
clock_drift = '10s'
max_block_time = '30s'
trusting_period = '9days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-2188'], # Coreum
   ['transfer', 'channel-75'], # Stargaze
   ['transfer', 'channel-208'], # Axelar
 ]
 

[[chains]]
id = 'stargaze-1'
type = 'CosmosSdk'
rpc_addr = 'http://127.0.0.1:27657'
grpc_addr = 'tcp://127.0.0.1:9092'
event_source = { mode = 'push', url = 'ws://127.0.0.1:27657/websocket', batch_delay = '200ms' }
rpc_timeout = '120s'
account_prefix = 'stars'
key_name = 'stargaze'
store_prefix = 'ibc'
max_gas = 5000000
gas_price = { price = 1, denom = 'ustars' }
gas_multiplier = 1.2
clock_drift = '20s'
max_block_time = '30s'
trusting_period = '9days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-0'], # Osmosis
   ['transfer', 'channel-49'], # Kaiyo
   ['transfer', 'channel-50'], # Axelar

 ]

[[chains]]
id = 'teritori-1'
type = 'CosmosSdk'
rpc_addr = 'http://192.168.1.155:27657'
grpc_addr = 'http://192.168.1.155:9092'
event_source = { mode = 'push', url = 'ws://192.168.1.155:27657/websocket', batch_delay = '200ms' }
rpc_timeout = '120s'
account_prefix = 'tori'
key_name = 'tori'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.0, denom = 'utori' }
gas_multiplier = 1.2
clock_drift ='5s'
max_block_time = '30s'
trusting_period = '1209600s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-10'], # cosmoshub
   ['transfer', 'channel-30'], # kujira
   ['transfer', 'channel-61'], # Axelar
]



