[global]
log_level = 'info'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = false

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 1000
clear_on_start = true
#filter = true
tx_confirmation = true

[telemetry]
enabled = true
host = 'X.X.X.X'
port = 3000

[[chains]]
id = 'axelar-dojo-1'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr = 'GRPC_ENDPOINT'
trusted_node = true
event_source = { mode = 'pull', interval = '100ms' }
rpc_timeout = '120s'
account_prefix = 'axelar'
key_name = 'axelar'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.01, denom = 'uaxl' }
gas_multiplier = 1.2
clock_drift ='5s'
max_block_time = '30s'
trusting_period = '403200s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-2'], # Cosmos-Hub
   ['transfer', 'channel-3'], # Osmosis
   ['transfer', 'channel-122'], # Teritori
   ['transfer', 'channel-14'], # Kujira
   ['transfer', 'channel-18'], # Stargaze
   ['transfer', 'channel-114'], # Ixo
   ['transfer', 'channel-120'], # Coreum
]

[[chains]]
id = "celestia"
compat_mode = '0.34'
type = "CosmosSdk"
rpc_addr = "RPC_ENDPOINT"
grpc_addr = "GRPC_ENDPOINT"
event_source = { mode = 'push', url = 'ws://RPC_ENDPOINT/websocket', batch_delay = '500ms' }
rpc_timeout = "120s"
account_prefix = "celestia"
key_name = "celestia-key"
store_prefix = "ibc"
gas_price = { price = 0.002, denom = 'utia' }
default_gas = 300000
max_gas = 6000000
gas_multiplier = 1.5
max_msg_num = 20
clock_drift = "5s"
max_block_time = "30s"
memo_prefix = 'Inter Blockchain Services Relayer'
trusting_period = '1209600seconds'
[chains.packet_filter]
 policy = 'allow'
 list = [
 ]


[[chains]]
id = 'coreum-mainnet-1'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr = 'GRPC_ENDPOINT'
trusted_node = true
event_source = { mode = 'pull', interval = '100ms' }
rpc_timeout = '120s'
account_prefix = 'core'
key_name = 'coreum'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.06, denom = 'ucore' }
gas_multiplier = 1.2
clock_drift ='5s'
max_block_time = '30s'
trusting_period = '403200s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-6'], # Axelar
   ['transfer', 'channel-2'], # Osmo
   ['transfer', 'channel-9'], # Cosmoshub
   ['transfer', 'channel-18'], # Kava
   ['transfer', 'channel-17'], # Kujira
]

[[chains]]
id = 'cosmoshub-4'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr = 'GRPC_ENDPOINT'
trusted_node = true
event_source = { mode = 'pull', interval = '100ms' }
rpc_timeout = '30s'
account_prefix = 'cosmos'
key_name = 'cosmos'
store_prefix = 'ibc'
max_tx_size = 180000
max_gas = 2000000
gas_price = { price = 0.005, denom = 'uatom' }
gas_multiplier = 1.2
clock_drift = '15s'
max_block_time = '30s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
  ['transfer', 'channel-660'], # Coreum
  ['transfer', 'channel-293'], # Axelar
  ['transfer', 'channel-343'], # Kujira
  ['transfer', 'channel-431'], # Teritori
  ['transfer', 'channel-204'], # ixo
]

[[chains]]
id = 'pacific-1'
compat_mode = '0.37'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr = 'GRPC_ENDPOINT'
event_source = { mode = 'pull', interval = '1s' }
rpc_timeout = '60s'
account_prefix = 'sei'
key_name = 'sei'
store_prefix = 'ibc'
max_tx_size = 180000
max_gas = 2000000
gas_price = { price = 0.1, denom = 'usei' }
gas_multiplier = 1.5
clock_drift = '70s'
trusting_period = '10days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
]

[[chains]]
id = 'ixo-5'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr =  'GRPC_ENDPOINT'
trusted_node = true
event_source = { mode = 'pull', interval = '100ms' }
rpc_timeout = '120s'
account_prefix = 'ixo'
key_name = 'ixo-5'
store_prefix = 'ibc'
default_gas = 200000
max_gas = 2000000
gas_price = { price = 0.5, denom = 'uixo' }
gas_multiplier = 1.3
clock_drift = '15s'
max_block_time = '30s'
trusting_period = '1209600s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-1'], # Cosmos
   ['transfer', 'channel-23'], # Axelar
   ['transfer', 'channel-25'], # Kava
]
 
[[chains]]
id = 'kaiyo-1'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'  
grpc_addr =  'GRPC_ENDPOINT'
event_source = { mode = 'pull', interval = '100ms' }
fee_granter = 'kujira1.....'
rpc_timeout = '120s'
account_prefix = 'kujira'
key_name = 'kujira'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.0034, denom = 'ukuji' }
gas_multiplier = 1.2
clock_drift = '5s'
max_block_time = '30s'
trusting_period = '806400s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-0'], # Cosmos-Hub
   ['transfer', 'channel-7'], # Stargaze
   ['transfer', 'channel-9'], # Axelar
   ['transfer', 'channel-89'], # Teritori
   ['transfer', 'channel-95'], # Kava
   ['transfer', 'channel-117'], # Celestia
   ['transfer', 'channel-122'], # Coreum
]

[[chains]]
id = 'kava_2222-10'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr = 'GRPC_ENDPOINT'
event_source = { mode = 'push', url = 'ws://RPC_ENDPOINT/websocket', batch_delay = '200ms' }
rpc_timeout = '120s'
account_prefix = 'kava'
key_name = 'kava'
store_prefix = 'ibc'
max_tx_size = 179000
max_gas = 10000000
gas_price = { price = 0.001, denom = 'ukava' }
gas_multiplier = 1.3
clock_drift = '25s'
max_block_time = '30s'
trusting_period = '1209600s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-128'], # Ixo
   ['transfer', 'channel-116'], # Kujira
   ['transfer', 'channel-142'], # Coreum
]

[[chains]]
id = 'osmosis-1'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr = 'GRPC_ENDPOINT'
event_source = { mode = 'pull', interval = '100ms' }
rpc_timeout = '120s'
account_prefix = 'osmo'
key_name = 'osmosis'
store_prefix = 'ibc'
gas_price_multiplier = 1.1
max_gas_price = 0.6
max_gas = 25000000
max_msg_num = 10
gas_price = { price = 0.025, denom = 'uosmo' }
gas_multiplier = 1.2
max_tx_size = 2097152
clock_drift = '10s'
max_block_time = '30s'
trusting_period = '9days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-2188'], # Coreum
   ['transfer', 'channel-75'], # Stargaze
   ['transfer', 'channel-208'], # Axelar
   ['transfer', 'channel-688'], # Quasar
 ]
 

[[chains]]
id = 'stargaze-1'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr = 'GRPC_ENDPOINT'
event_source = { mode = 'pull', interval = '100ms' }
rpc_timeout = '120s'
account_prefix = 'stars'
key_name = 'stargaze'
store_prefix = 'ibc'
max_gas = 5000000
gas_price = { price = 1, denom = 'ustars' }
gas_multiplier = 1.2
clock_drift = '20s'
max_block_time = '30s'
trusting_period = '9days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-0'], # Osmosis
   ['transfer', 'channel-49'], # Kaiyo
   ['transfer', 'channel-50'], # Axelar

 ]

[[chains]]
id = 'teritori-1'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr = 'RPC_ENDPOINT'
event_source = { mode = 'pull', interval = '100ms' }
rpc_timeout = '120s'
account_prefix = 'tori'
key_name = 'tori'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.0, denom = 'utori' }
gas_multiplier = 1.2
clock_drift ='5s'
max_block_time = '30s'
trusting_period = '1209600s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-10'], # cosmoshub
   ['transfer', 'channel-30'], # kujira
   ['transfer', 'channel-61'], # Axelar
]

[[chains]]
id = 'quasar-1'
type = 'CosmosSdk'
rpc_addr = 'RPC_ENDPOINT'
grpc_addr = 'GRPC_ENDPOINT'event_source = { mode = 'pull', interval = '100ms' }
rpc_timeout = '120s'
account_prefix = 'quasar'
key_name = 'quasar'
store_prefix = 'ibc'
max_tx_size = 179000
max_gas = 3000000
gas_price = { price = 0.1, denom = 'uqsr' }
gas_multiplier = 1.3
clock_drift = '25s'
max_block_time = '30s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-0'], # Cosmos
   ['transfer', 'channel-1'], # Osmosis
]