[global]
log_level = 'info'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = false

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 1000
clear_on_start = false
#filter = true
tx_confirmation = true

[telemetry]
enabled = true
host = '192.168.1.113'
port = 3000

[[chains]]
id = 'laozi-mainnet'
type = 'CosmosSdk'
rpc_addr =  'http://192.168.1.56:27657'    
grpc_addr =   'tcp://192.168.1.56:9790'   
event_source = { mode = 'push', url = 'ws://192.168.1.56:27657/websocket', batch_delay = '200ms' }
rpc_timeout = '120s'
account_prefix = 'band'
key_name = 'band'
store_prefix = 'ibc'
#max_tx_size = 180000
max_gas = 2000000
gas_price = { price = 0.0025, denom = 'uband' }
gas_multiplier = 1.2
clock_drift = '895s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['oracle', 'channel-157'], # Desmos
   ['transfer', 'channel-83'], # Osmosis
]

[[chains]]
id = 'coreum-mainnet-1'
type = 'CosmosSdk'
rpc_addr = 'http://192.168.1.55:27657'
grpc_addr = 'http://192.168.1.55:9092'
event_source = { mode = 'push', url = 'ws://192.168.1.55:27657/websocket', batch_delay = '200ms' }
rpc_timeout = '120s'
account_prefix = 'core'
key_name = 'coreum'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.06, denom = 'ucore' }
gas_multiplier = 1.5
clock_drift ='5s'
trusting_period = '1209600s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-7'], # Gravity
   ['transfer', 'channel-8'], # evmos
]

[[chains]]
id = 'cosmoshub-4'
type = 'CosmosSdk'
rpc_addr = 'http://192.168.1.250:33657'
grpc_addr = 'http://192.168.1.250:9098'
event_source = { mode = 'push', url = 'ws://192.168.1.250:33657/websocket', batch_delay = '200ms' }
rpc_timeout = '20s'
account_prefix = 'cosmos'
key_name = 'cosmos'
store_prefix = 'ibc'
max_msg_num = 5
max_tx_size = 180000
max_gas = 2000000
default_gas = 1000000
gas_price = { price = 0.00, denom = 'uatom' }
gas_multiplier = 1.5
clock_drift = '15s'
trusting_period = '1209600s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
  ['icahost', 'channel-604'], # lum pool 1 deposit
  ['icahost', 'channel-605'], # lum pool 2 deposit
  ['icahost', 'channel-606'], # lum pool 1 prizepool
  ['icahost', 'channel-607'], # lum pool 2 prizepool

]

[[chains]]
id = 'desmos-mainnet'
type = 'CosmosSdk'
rpc_addr = 'http://192.168.1.40:26657'
grpc_addr = 'tcp://192.168.1.40:9090'
event_source = { mode = 'push', url = 'ws://192.168.1.40:26657/websocket', batch_delay = '200ms' }
rpc_timeout = '120s'
account_prefix = 'desmos'
key_name = 'desmos'
store_prefix = 'ibc'
max_gas = 4000000
gas_price = { price = 0.01, denom = 'udsm' }
gas_multiplier = 1.2
clock_drift = '25s'
trusting_period = '9days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-2'], # Osmosis
   ['ibc-profiles', 'channel-32'], # Band
]

[[chains]]
id = 'evmos_9001-2'
type = 'CosmosSdk'
rpc_addr =  'http://192.168.190:26657'  
grpc_addr = 'tcp://192.168.190:9090'
event_source = { mode = 'pull', interval = '1s' }
account_prefix = 'evmos'
key_name = 'evmos'
store_prefix = 'ibc'
max_tx_size = 180000
max_gas = 3000000
gas_price = { price = 20000000000, denom = 'aevmos' }
gas_multiplier = 2
clock_drift = '50s'
trusting_period = '84hours'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
address_type = { derivation = 'ethermint', proto_type = { pk_type = '/ethermint.crypto.v1.ethsecp256k1.PubKey' } }
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-87'] # coreum
]

[[chains]]
id = 'gravity-bridge-3'
type = 'CosmosSdk'
rpc_addr = 'http://192.168.1.37:26657'  
grpc_addr = 'http://192.168.1.37:9090'
event_source = { mode = 'push', url = 'ws://192.168.1.37:26657/websocket', batch_delay = '200ms' }
rpc_timeout = '120s'
account_prefix = 'gravity'
key_name = 'grav'
store_prefix = 'ibc'
max_gas = 1200000
gas_price = { price = 0.001, denom = 'ugraviton' }
gas_multiplier = 1.2
clock_drift ='555s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-10'], # Osmosis
   ['transfer', 'channel-107'], # Kujira
   ['transfer', 'channel-142'], #coreum
]

[[chains]]
id = 'kaiyo-1'
type = 'CosmosSdk'
rpc_addr = 'http://192.168.1.250:28657'
grpc_addr =  'tcp://192.168.1.250:9093'
event_source = { mode = 'push', url = 'ws://192.168.1.250:28657/websocket', batch_delay = '200ms' }
fee_granter = 'kujira1vkje22mayn72r0a7kna6agv0sqm6k94ry9k6dd'
rpc_timeout = '120s'
account_prefix = 'kujira'
key_name = 'kujira'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.00125, denom = 'ukuji' }
gas_multiplier = 1.2
clock_drift = '5s'
trusting_period = '9days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-3'], # Osmosis
   ['transfer', 'channel-50'], # Gravity
   ['transfer', 'channel-95'], # kava

]

[[chains]]
id = 'kava_2222-10'
type = 'CosmosSdk'
rpc_addr = 'http://192.168.1.54:26657'
grpc_addr = 'tcp://192.168.1.54:9090'
event_source = { mode = 'push', url = 'ws://192.168.1.54:26657/websocket', batch_delay = '200ms' }
rpc_timeout = '120s'
account_prefix = 'kava'
key_name = 'kava'
store_prefix = 'ibc'
max_tx_size = 179000
max_gas = 3000000
gas_price = { price = 0.003, denom = 'ukava' }
gas_multiplier = 1.3
clock_drift = '25s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-116'], # Kujira
]

[[chains]]
id = 'lum-network-1'
type = 'CosmosSdk'
rpc_addr = 'http://192.168.1.116:27657'
grpc_addr = 'http://192.168.1.116:9190'
event_source = { mode = 'push', url = 'ws://192.168.1.116:27657/websocket', batch_delay = '200ms' }
rpc_timeout = '120s'
account_prefix = 'lum'
key_name = 'lum'
store_prefix = 'ibc'
max_gas = 1200000
gas_price = { price = 0.001, denom = 'ulum' }
gas_multiplier = 1.2
clock_drift ='15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-3'], # osmosis
   ['icacontroller-pool.1.deposit', 'channel-13'], # ica cosmos 
   ['icacontroller-pool.2.deposit', 'channel-14'], # ica cosmos
   ['icacontroller-pool.1.prizepool', 'channel-15'], # ica cosmos
   ['icacontroller-pool.2.prizepool', 'channel-16'], # ica cosmos

]

[[chains]]
id = 'osmosis-1'
type = 'CosmosSdk'
rpc_addr = 'http://192.168.1.126:26657'
grpc_addr = 'tcp://192.168.1.126:9090'
event_source = { mode = 'pull', interval = '1s' }
rpc_timeout = '120s'
account_prefix = 'osmo'
key_name = 'osmosis'
store_prefix = 'ibc'
max_gas = 12000000
max_msg_num = 30
gas_price = { price = 0.0025, denom = 'uosmo' }
gas_multiplier = 1.5
max_tx_size = 1800000
clock_drift = '15s'
trusting_period = '9days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-115'], # Lum
   ['transfer', 'channel-135'], # Desmos
   ['transfer', 'channel-144'], # Gravity
   ['transfer', 'channel-148'], # Band
   ['transfer', 'channel-221'], # Rizon
   ['transfer', 'channel-259'], # Kujira
   ['transfer', 'channel-362'], # teritori
 ]

[[chains]]
id = 'titan-1'
type = 'CosmosSdk'
rpc_addr = 'http://192.168.1.116:26657/'
grpc_addr = 'tcp://192.168.1.116:9090'
event_source = { mode = 'push', url = 'ws://192.168.1.116:26657/websocket', batch_delay = '200ms' }
rpc_timeout = '120s'
account_prefix = 'rizon'
key_name = 'rizon'
store_prefix = 'ibc'
max_gas = 6000000
max_msg_num = 10
gas_price = { price = 0.0001, denom = 'uatolo' }
gas_multiplier = 1.2
clock_drift = '5s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-1'], # osmosis
]

[[chains]]
id = 'teritori-1'
type = 'CosmosSdk'
rpc_addr = 'http://192.168.1.155:27657'
grpc_addr = 'http://192.168.1.155:9092'
event_source = { mode = 'push', url = 'ws://192.168.1.155:27657/websocket', batch_delay = '200ms' }
rpc_timeout = '120s'
account_prefix = 'tori'
key_name = 'tori'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.001, denom = 'utori' }
gas_multiplier = 1.2
clock_drift ='5s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-0'], # osmo
]
