[global]
log_level = 'info'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = false

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 1000
clear_on_start = false
#filter = true
tx_confirmation = true

[telemetry]
enabled = true
host = '192.168.1.111'
port = 3000

[[chains]]
id = 'axelar-dojo-1'
type = 'CosmosSdk'
rpc_addr = 'http://192.168.1.250:32657'
grpc_addr = 'http://192.168.1.250:9097'
event_source = { mode = 'push', url = 'ws://192.168.1.250:32657/websocket', batch_delay = '500ms' }
rpc_timeout = '120s'
account_prefix = 'axelar'
key_name = 'axelar'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.007, denom = 'uaxl' }
gas_multiplier = 1.2
clock_drift ='5s'
trusting_period = '5days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-17'], # Ki
   ['transfer', 'channel-21'], # Fetch
   ['transfer', 'channel-32'], # Bitcanna
   ['transfer', 'channel-75'], # Kyve
]

[[chains]]
id = 'bitcanna-1'
type = 'CosmosSdk'
rpc_addr = 'http://192.168.1.53:27657' 
grpc_addr = 'http://192.168.1.53:9092/' 
event_source = { mode = 'push', url = 'ws://192.168.1.53:27657/websocket', batch_delay = '500ms' }
rpc_timeout = '120s'
account_prefix = 'bcna'
key_name = 'bcna'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.01, denom = 'ubcna' }
gas_multiplier = 1.2
clock_drift = '10s'
trusting_period = '806400s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-1'], # osmosis
   ['transfer', 'channel-3'], # cosmos
   ['transfer', 'channel-8'], # gravity
   ['transfer', 'channel-15'], # axelar
]

[[chains]]
id = 'cosmoshub-4'
type = 'CosmosSdk'
rpc_addr = 'http://192.168.1.250:33657'   #'https://rpc-cosmoshub.blockapsis.com:443'   #'http://192.168.1.250:33657'
grpc_addr = 'http://192.168.1.250:9098'
event_source = { mode = 'push', url = 'ws://192.168.1.250:33657/websocket', batch_delay = '500ms' }
rpc_timeout = '30s'
account_prefix = 'cosmos'
key_name = 'cosmos'
store_prefix = 'ibc'
max_tx_size = 180000
max_gas = 2000000
gas_price = { price = 0.00, denom = 'uatom' }
gas_multiplier = 1.2
clock_drift = '10s'
trusting_period = '806400s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
  ['transfer', 'channel-223'], # Kichain
  ['transfer', 'channel-232'], # Bitcanna
  ['transfer', 'channel-277'], # Kava
  ['transfer', 'channel-526'], # Fetch
]

[[chains]]
id = 'fetchhub-4'
type = 'CosmosSdk'
rpc_addr = 'http://192.168.1.106:27657/'
grpc_addr = 'tcp://192.168.1.106:9092'
event_source = { mode = 'push', url = 'ws://192.168.1.106:27657/websocket', batch_delay = '500ms' }
rpc_timeout = '120s'
account_prefix = 'fetch'
key_name = 'fetch'
store_prefix = 'ibc'
max_tx_size = 179000
max_gas = 2000000
gas_price = { price = 2, denom = 'afet' }
gas_multiplier = 1.2
clock_drift = '10s'
trusting_period = '1209600s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services (former 3Tekos) Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-10'], # Osmosis
   ['transfer', 'channel-14'], # Axelar
   ['transfer', 'channel-16'], # Cosmoshub
]

[[chains]]
id = 'gitopia'
type = 'CosmosSdk'
rpc_addr = 'http://192.168.1.155:26657'
grpc_addr = 'http://192.168.1.155:9090'
event_source = { mode = 'push', url = 'ws://192.168.1.155:26657/websocket', batch_delay = '500ms' }
rpc_timeout = '120s'
account_prefix = 'gitopia'
key_name = 'gitopia'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.0, denom = 'ulore' }
gas_multiplier = 1.5
clock_drift ='5s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-0'], # osmo
]


[[chains]]
id = 'gravity-bridge-3'
type = 'CosmosSdk'
rpc_addr = 'http://192.168.1.37:26657'
grpc_addr = 'http://192.168.1.37:9090'
event_source = { mode = 'push', url = 'ws://192.168.1.37:26657/websocket', batch_delay = '500ms' }
rpc_timeout = '120s'
account_prefix = 'gravity'
key_name = 'grav'
store_prefix = 'ibc'
max_gas = 1200000
gas_price = { price = 0.001, denom = 'ugraviton' }
gas_multiplier = 1.2
clock_drift ='15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-0'], # Bitcanna
#   ['transfer', 'channel-8'], # Juno
   ['transfer', 'channel-37'], # Kichain
]

[[chains]]
id = 'kava_2222-10'
type = 'CosmosSdk'
rpc_addr = 'http://192.168.1.54:26657'
grpc_addr = 'tcp://192.168.1.54:9090'
event_source = { mode = 'push', url = 'ws://192.168.1.54:26657/websocket', batch_delay = '500ms' }
rpc_timeout = '120s'
account_prefix = 'kava'
key_name = 'kava'
store_prefix = 'ibc'
max_tx_size = 179000
max_gas = 3000000
gas_price = { price = 0.003, denom = 'ukava' }
gas_multiplier = 1.3
clock_drift = '25s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-0'], # Cosmos
   ['transfer', 'channel-1'], # Osmosis
]

[[chains]]
id = 'kichain-2'
type = 'CosmosSdk'
rpc_addr = 'http://192.168.1.35:27657'
grpc_addr = 'tcp://192.168.1.35:9094'
event_source = { mode = 'push', url = 'ws://192.168.1.35:27657/websocket', batch_delay = '500ms' }
rpc_timeout = '120s'
account_prefix = 'ki'
key_name = 'ki'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.025, denom = 'uxki' }
gas_multiplier = 1.2
clock_drift = '25s'
trusting_period = '9days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-0'], # Osmosis
   ['transfer', 'channel-1'], # Cosmos
   ['transfer', 'channel-11'], # Gravity
   ['transfer', 'channel-19'], # Axelar
   ['wasm.ki1hzz0s0ucrhdp6tue2lxk3c03nj6f60qy463we7lgx0wudd72ctmsd9kgha ', 'channel-18'], # Osmosis-CW20


]

[[chains]]
id = 'osmosis-1'
type = 'CosmosSdk'
rpc_addr =  'http://192.168.1.126:26657'
grpc_addr =  'tcp://192.168.1.126:9090'
event_source = { mode = 'pull', interval = '1s' }
rpc_timeout = '120s'
account_prefix = 'osmo'
key_name = 'osmosis'
store_prefix = 'ibc'
max_gas = 120000000
max_msg_num = 30
gas_price = { price = 0.0025, denom = 'uosmo' }
gas_multiplier = 1.5
default_gas = 400000
max_tx_size = 1800000
clock_drift = '5s'
trusting_period = '9days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-51'], # bitcanna
   ['transfer', 'channel-77'], # kichain
   ['transfer', 'channel-143'], # kava
   ['transfer', 'channel-229'], # Fetch
   ['transfer', 'channel-767'], # Kyve
   ['transfer', 'channel-261'], # Ki CW20
   ['transfer', 'channel-781'], # gitopia
   ['transfer', 'channel-2494'], # passage
]

[[chains]]
id = 'passage-2'
type = 'CosmosSdk'
rpc_addr = 'https://passage-rpc.ibs.team:443'
grpc_addr = 'http://passage-grpc.ibs.team:9990'
event_source = { mode = 'push', url = 'wss://passage-rpc.ibs.team:443/websocket', batch_delay = '500ms' }
rpc_timeout = '120s'
account_prefix = 'pasg'
key_name = 'passage'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.0, denom = 'upasg' }
gas_multiplier = 1.5
clock_drift ='5s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-0'], # osmo
]


[[chains]]
id = 'kyve-1'
type = 'CosmosSdk'
rpc_addr =  'http://192.168.1.55:26657'
grpc_addr =  'tcp://192.168.1.55:9090'
event_source = { mode = 'push', url = 'ws://192.168.1.55:26657/websocket', batch_delay = '500ms' }
rpc_timeout = '120s'
account_prefix = 'kyve'
key_name = 'kyve'
store_prefix = 'ibc'
max_gas = 2000000
max_msg_num = 30
gas_price = { price = 0.02, denom = 'ukyve' }
gas_multiplier = 1.5
default_gas = 500000
max_tx_size = 1800000
clock_drift = '15s'
trusting_period = '1209600s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Inter Blockchain Services Relayer'
[chains.packet_filter]
 policy = 'allow'
 list = [
   ['transfer', 'channel-0'], # osmosis
   ['transfer', 'channel-1'], # axelar

]

